export const permissions = {
    ALL_PERMISSIONS: 'ALL_PERMISSIONS',
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',
    VIEW_REQUESTS: 'VIEW_REQUESTS',
    VIEW_BRANDS: 'VIEW_BRANDS',
    VIEW_USERS: 'VIEW_USERS',
    VIEW_CLIENTS: 'VIEW_CLIENTS',
};